### ISSUE TITLE
Can not click items on the sidebar

### ISSUE THREAD

**Issue by bjrmatos** [jaywcjlove/rightmenu-master#3]
### 🙋‍♂️ How can we help you?

i just installed from app store but can not click/select any of the items on the sidebar

i can not open or select any of the items on the sidebar.

permissions are enabled and also the cli command with pluginkit was executed.

is this expected? what can be the issue? 

### 💻 Desktop

macOS 14.6.1 (Sonoma)

### ℹ️ Additional context

![Screenshot 2024-11-11 at 11  23 16@2x](https://github.com/user-attachments/assets/ca5cd92f-e4c5-4153-b401-de6055d0340e)

**Comment by jaywcjlove** [comment]
@bjrmatos  I couldn’t reproduce this error on my machine (macOS 15.0.1). Based on a similar issue I encountered in another app, I noticed that your current system version is macOS Sonoma 14.6.1. I recommend updating to version 14.7 to see if it resolves the problem.

The implementation of this menu feature is relatively simple, mainly involving data sharing with the Finder extension, so it’s unclear if this is the cause of the issue.

Additionally, macOS Sonoma 14.7 includes important security fixes, so it’s advised for all users to update to this version.

**Comment by bjrmatos** [comment]
i have updated to macOS Sonomoa 14.7.1 today, but still the same issue, you can see this video of me trying to click the menu items, not sure what can be the problem, other apps with this kind of sidebar work for me, it is just RightMenu master which has this issue.

video: https://share.cleanshot.com/DzX9KrFh

**Comment by jaywcjlove** [comment]
@bjrmatos I developed it on macOS 15, but now I need to find a way to debug it on macOS Sonoma 14.

**Comment by jaywcjlove** [comment]
<img width="727" alt="image" src="https://github.com/user-attachments/assets/830264ca-e3b0-4f69-8cb6-9ed1f8069178">

I found an issue where the QuickLook extension was not set to be compatible with macOS 14. I have now fixed this and updated the compatibility. Version 1.1 is currently being released. Once the release is complete, please update and check if the issue has been resolved.

@bjrmatos

**Comment by bjrmatos** [comment]
@jaywcjlove thanks, i will try when it is available

**Comment by jaywcjlove** [comment]
@bjrmatos Version 1.1 has been released. Please update and check if the issue is resolved.

**Comment by jaywcjlove** [comment]
@bjrmatos  I identified the issue in the virtual machine and have submitted the latest v1.2.0 version, which resolves the problem. It is currently awaiting review.

**Comment by bjrmatos** [comment]
nice, i can finally use the app at its full potential! thanks, i confirm it works now
