### ISSUE TITLE
🙋‍♂️ Support & Feedback: menu not appear as expected inside in a smb dir

### ISSUE THREAD

**Issue by qwejdl2378** [jaywcjlove/rightmenu-master#6]
### 🙋‍♂️ How can we help you?

when i do right click inside in a smb dir ,  right menu not appear as expected, but everything ok when i do right click on system volume
<img width="801" alt="expected" src="https://github.com/user-attachments/assets/f2d9a46c-cd01-443e-a5ee-1837cdf08531">
<img width="793" alt="no expected" src="https://github.com/user-attachments/assets/89e882a6-6e4a-4f39-9c8f-33e8ee4c09d4">

### 💻 Desktop

macOS 15.0 (Sequoia)

**Comment by jaywcjlove** [comment]
@qwejdl2378 I’ve figured out the problem and will try to resolve it.

**Comment by jaywcjlove** [comment]
@qwejdl2378 v1.7 has been submitted and is awaiting review. The issues encountered during testing have been resolved.

**Comment by qwejdl2378** [comment]
when this release passed i will try as soon as i can and give my feedback. 
thank you for your excellent job

**Comment by jaywcjlove** [comment]
@qwejdl2378 🎉 v1.7.0 is out now!

**Comment by qwejdl2378** [comment]
apologize for the late feedback
rightmenu work well now at my smb volume 
<img width="683" alt="截屏2024-12-14 01 15 00" src="https://github.com/user-attachments/assets/36335703-0d33-4698-a6b8-29a2bc0778ef" />
