### ISSUE TITLE
🙋‍♂️ 支持与反馈: RightMenu Master

### ISSUE THREAD

**Issue by guoguoguilai** [jaywcjlove/rightmenu-master#7]
### 🙋‍♂️ 您需要什么帮助？

给了完全磁盘访问权限后，包括也添加了对应文件夹，但还是无法看到对应的菜单项。系统应该是15.1，刚升级了15.2，问题也存在

### 💻 桌面

macOS 15.0 (Sequoia)

### ℹ️ 补充说明

<img width="829" alt="image" src="https://github.com/user-attachments/assets/546fd470-d220-4bb5-9537-3244c8cdcf69" />
<img width="494" alt="image" src="https://github.com/user-attachments/assets/4284c4dc-119e-4894-a43e-188c098ec6b2" />

**Comment by jaywcjlove** [comment]
@guoguoguilai 你升级 v1.8 试一试，我无法重现这个问题

**Comment by guoguoguilai** [comment]
> @guoguoguilai 你升级 v1.8 试一试，我无法重现这个问题

升级了1.8以后，这个问题消失了
